name: CI/CD for React App

on:
  push:
    branches:
      - main   # Trigger workflow on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger workflow on pull requests to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Specify the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure the build-and-test job passes first
    if: github.ref == 'refs/heads/main'  # Deploy only on the main branch

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to Production
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Specify the branch for deployment
        folder: build     # Path to the React build output
